starter_kit_start:
    resource: "@StarterKitStartBundle/Resources/config/routing.yml"

login_check:
    path: login_check

admin:
    resource: "@AppBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin

main:
    resource: '@AppBundle/Controller/Main/'
    type: annotation
    prefix: /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
