login_check:
    path: login_check

starter_kit_start_security_api_routes:
    resource: '@StarterKitStartBundle/Controller/SecurityController.php'
    type: annotation
    prefix: /


starter_kit_start_user_api_routes:
    resource: '@StarterKitStartBundle/Controller/UserController.php'
    type: annotation
    prefix: /api
